- name: Get IP Address for HAProxy Machine
  set_fact: 
    haproxy_ip="{{ hostvars[item].ansible_ens2.ipv4.address }}"
  when: "{{ hostvars[item].haproxy is defined }}"
  with_items: 
  - "{{ groups['k8s_vms' + msetnumber + '_' + servernumber] }}"
- name: Wait for HAProxy service to be ready
  wait_for:
    port: 80
    host: "{{ haproxy_ip }}"
    connect_timeout: 3
    delay: 3
    timeout: 300
- name: Initializing Kubernetes cluster
  shell: kubeadm init --control-plane-endpoint {{ haproxy_ip }}:80 --upload-certs --apiserver-advertise-address {{ ansible_ens2.ipv4.address }} --skip-phases=addon/kube-proxy --skip-phases=addon/coredns --ignore-preflight-errors=NumCPU
  register: output
- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest="./token"
- name: Create .kube directory
  become: yes
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
